Iter9
4aleksei/metricscum pull request #11
Opened 2024-12-18 15:10 UTC by 4aleksei

iter9 no fix lint

2024-12-22 08:57 UTC, zhark0vv requested changes

2024-12-22 08:57 UTC, zhark0vv commented on internal/common/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Рекомендую здесь избавиться от глобального состояния логгера.

Смотри, ты используешь Singleton, у тебя есть один глобальный логгер.
Но в Go это антипаттерн. И причин этому две:

- существование концепции поинтеров
- duck-typing

В Go очень хорошо реализуется классический DI, а отсутствие новых объектов гарантируется поинтерами.
Здесь стоит сделать просто обертку, ее конструктор, создать объект логгера в main-пакете и инжетировать ее туда, где она нужна.

Знаю, что так сделано в учебных материалах.
Пример дан для демонстрации. Обычно мы стараемся избегать глобальных зависимостей.

Рекомендую тебе разобраться детальнее с концепцией Dependency Injection и встроить логгер туда, где он нужен явно.

2024-12-22 08:57 UTC, zhark0vv commented on internal/common/repository/repository.go
> +const WriteIntervalDefault int64 = 300
const (
...
)

2024-12-22 08:57 UTC, zhark0vv commented on internal/server/handlers/handlers_test.go
> +		//{name: "Test No3", req: request{method: http.MethodPost, url: "/update/"}, want: want{statusCode: http.StatusNotFound, contentType: "text/plain; charset=utf-8"}},
Лишние комментарии.

2024-12-22 08:57 UTC, zhark0vv commented on internal/server/service/service.go
>  type ServerMetricsStorage interface {
Пусть этот интерфейс будет приватным для пакета.
Он же локальный.

2024-12-22 08:57 UTC, zhark0vv commented on internal/common/filesreadwrite/filesreadwrite.go
> +	file, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, defaultMode)
Пусть продюсер/консьюмер принимает io типы, а уже потребитель решит, что это будет: файл или что-то другое.

2024-12-22 08:57 UTC, zhark0vv commented on internal/agent/service/service.go
> +		data := typename + "/" + key + "/" + valstr
`fmt.Sprintf` будет читабельнее здесь.

2024-12-26 23:37 UTC, 4aleksei commented on internal/agent/service/service.go
> +		data := typename + "/" + key + "/" + valstr
done

2024-12-26 23:59 UTC, 4aleksei commented on internal/server/handlers/handlers_test.go
> +		//{name: "Test No3", req: request{method: http.MethodPost, url: "/update/"}, want: want{statusCode: http.StatusNotFound, contentType: "text/plain; charset=utf-8"}},
done.

2024-12-26 23:59 UTC, 4aleksei commented on internal/server/service/service.go
>  type ServerMetricsStorage interface {
done

2024-12-26 23:59 UTC, 4aleksei commented on internal/common/repository/repository.go
> +const WriteIntervalDefault int64 = 300
done

2024-12-27 00:04 UTC, 4aleksei commented on internal/common/filesreadwrite/filesreadwrite.go
> +	file, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, defaultMode)
done. переделал , теперь все обработчики принимают io.Read или io.Write

2024-12-27 00:05 UTC, 4aleksei commented on internal/common/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
done. передаю указатель на логгер во все воркеры

2024-12-27 07:35 UTC, zhark0vv approved these changes

2025-01-07 08:46 UTC, merged