Iter5
4aleksei/metricscum pull request #7
Opened 2024-12-04 12:34 UTC by 4aleksei

2024-12-04 14:10 UTC, 4aleksei commented
Тесты не дописаны, не успел . спешил сдать до iter5

2024-12-06 14:05 UTC, zhark0vv requested changes

2024-12-06 14:05 UTC, zhark0vv commented on internal/common/repository/repository.go
> +		mux:   &sync.Mutex{},
Поинтеры более принято создавать через `new`

2024-12-06 14:05 UTC, zhark0vv commented on internal/server/handlers/handlers.go
> +func Serve(store *service.HandlerStore, cfg *config.Config) error {
Рекомендую сделать `Serve` методом `handlers`, а также сделать `handlers` публичной структурой.

2024-12-10 00:03 UTC, 4aleksei commented on internal/agent/config/config.go
> +			fmt.Println("Error in converting env report interval to int: ", err)
done

2024-12-10 00:03 UTC, 4aleksei commented on internal/agent/handlers/handlers.go
> +	//client := http.Client{}
done

2024-12-10 00:03 UTC, 4aleksei commented on internal/common/repository/repository.go
> +type MetricsStorage interface {
done

2024-12-10 00:04 UTC, 4aleksei commented on internal/server/service/service.go
> +func RecieveGauge(store repository.MetricsStorage, name string, valstr string) error {
done

2024-12-10 00:04 UTC, 4aleksei commented on internal/agent/gather/gather.go
> +func MainGather(store *service.HandlerStore, cfg *config.Config) error {
done

2024-12-10 00:04 UTC, 4aleksei commented on internal/common/repository/repository.go
> +	} else {
done

2024-12-10 00:09 UTC, 4aleksei commented on internal/common/repository/repository.go
> +	gauge   map[string]GaugeMetric
done , Частично использовал идею из runtime/metrics  "type Value struct"  , но код усложнился и утяжелился , видимо для большого количества типов для хранения такой подход будет лучше.

2024-12-10 00:09 UTC, 4aleksei commented on internal/server/handlers/handlers.go
> +func Serve(store *service.HandlerStore, cfg *config.Config) error {
done

2024-12-10 00:22 UTC, 4aleksei commented on internal/common/repository/repository.go
> +		mux:   &sync.Mutex{},
done , заменил везде &{...} на new()

2024-12-10 07:49 UTC, zhark0vv approved these changes

2024-12-10 07:49 UTC, zhark0vv commented on cmd/agent/main.go
> +	MainHTTPClient := handlers.NewApp(metricsService, cfg)
В Go есть одно простое правило - большая буква = экспортируемая переменная.
Использование приватных имен с заглавной буквы стоит исправить.

2024-12-10 07:49 UTC, zhark0vv commented on internal/common/repository/repository.go
> +	p := new(MemStorage)
В этих кейсах исправление необязательно.
new используется при инициализации пустого поинтера.

Здесь можно было бы ограничиться:

```
return &MemStorage{
values: ...
}
```

2024-12-10 07:49 UTC, zhark0vv commented on internal/server/handlers/handlers.go
> +	srv := &http.Server{
Создание сервера лучше унести в конструктор, а srv сделать зависимостью `HandlersServer`

2024-12-10 08:20 UTC, zhark0vv approved these changes

2024-12-10 11:41 UTC, merged